'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RFID_interface.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1355169() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355169", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13551691() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13551691", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1393568_200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1393568-200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _18372() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("18372", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _205574_200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("205574-200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _24235606_cv_icone_vecteur_reprendre_illustration_signe_utilisateur_les_donnees_symbole_ou_logo_vectoriel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("24235606-cv-icone-vecteur-reprendre-illustration-signe-utilisateur-les-donnees-sy"& _ 
                        "mbole-ou-logo-vectoriel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _24235927_cv_icone_vecteur_reprendre_illustration_signe_utilisateur_les_donnees_symbole_ou_logo_vectoriel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("24235927-cv-icone-vecteur-reprendre-illustration-signe-utilisateur-les-donnees-sy"& _ 
                        "mbole-ou-logo-vectoriel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _26823018_enquete_les_donnees_icone_icone_en_relation_a_enquete_ligne_icone_style_facile_vecteur_conception_modifiable_vectoriel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("26823018-enquete-les-donnees-icone-icone-en-relation-a-enquete-ligne-icone-style-"& _ 
                        "facile-vecteur-conception-modifiable-vectoriel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3056329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3056329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4274231_input_icon_asset_data_save_or_download_icon_glyph_symbol_in_your_web_site_design_logo_app_ui_webinar_video_chat_ect_vector_vectoriel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4274231-input-icon-asset-data-save-or-download-icon-glyph-symbol-in-your-web-site"& _ 
                        "-design-logo-app-ui-webinar-video-chat-ect-vector-vectoriel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4917538_200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4917538-200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _66318214_icône_ou_logo_de_base_de_données_dans_un_style_de_ligne_moderne_pictogramme_noir_de_haute_qualité() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("66318214-icône-ou-logo-de-base-de-données-dans-un-style-de-ligne-moderne-pictogra"& _ 
                        "mme-noir-de-haute-qualité", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property database_settings_glyph_black_icon_png_291832() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database-settings-glyph-black-icon-png_291832", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Disconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disconnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_arrow138_216456() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_arrow138_216456", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_Computer__Computer_Hardware_USB_Port_Connection_4064143_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_Computer__Computer_Hardware_USB_Port_Connection_4064143(1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_Computer__Computer_Hardware_USB_Port_Connection_4064143_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_Computer__Computer_Hardware_USB_Port_Connection_4064143(1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_document_text_accept_103510_2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_document_text_accept_103510(2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_1323174166_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-1323174166-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property profiles_icon_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profiles-icon-17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sticker_png_person_personal_data_logo_symbol_user_profile_head_text_line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sticker-png-person-personal-data-logo-symbol-user-profile-head-text-line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sticker_png_person_personal_data_logo_symbol_user_profile_head_text_line1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sticker-png-person-personal-data-logo-symbol-user-profile-head-text-line1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property userrfid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("userrfid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users_icon_data_archive_illustration_sign_database_symbol_user_data_logo_vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users-icon-data-archive-illustration-sign-database-symbol-user-data-logo-vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
